# Generated by Django 5.2.3 on 2025-07-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del edificio')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('tipo', models.CharField(choices=[('Comercial', 'Comercial'), ('Residencial', 'Residencial')], max_length=20, verbose_name='Tipo de edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número o identificador del dpto.')),
                ('numero_cuartos', models.PositiveIntegerField(verbose_name='Número de cuartos')),
                ('nombre_propietario', models.CharField(max_length=100, verbose_name='Nombre del propietario')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo mensual')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='app1.edificio')),
            ],
        ),
    ]
