# Generated by Django 5.2.3 on 2025-07-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='numero',
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('Comercial', 'comercial'), ('Residencial', 'residencial')], max_length=20, verbose_name='Tipo de edificio'),
        ),
    ]
