# Generated by Django 5.2.3 on 2025-07-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_departamento_numero_alter_edificio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre_propietario',
            field=models.CharField(max_length=100, verbose_name='Nombre completo del propietario'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('comercial', 'comercial'), ('residencial', 'residencial')], max_length=20, verbose_name='Tipo de edificio'),
        ),
    ]
